title: "Carolina Dulcien"
name: "Carolina Dulcien"
description: "PhD Student in Astronomy"

url: "https://carolinadulcien.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Carolina Dulcien"
  bio: "PhD Student in Astronomy"
  location: "Chile"
  email: "carolina.dulcien01@gmail.com"

markdown: kramdown
